name: CI
permissions: read-all


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install accel-config
      run: sudo apt install -y accel-config libaccel-config-dev
    - name: Install uuid
      run: sudo apt install -y uuid-dev
    - name: Install libnum
      run: sudo apt install -y libnuma-dev
    - name: make
      run: make
    - name: install
      run: sudo make install
    - name: make dto-test
      run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib64/; make dto-test
